name = "ftour-bab-rayan-v2"
main = "worker/index.ts"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Workers Builds uses this implicitly, but keep for clarity
[build]
command = "pnpm run build"

[vars]
NODE_ENV = "production"
