-- GENERATED by scripts/gen-d1-from-supabase.mjs. Do not edit.
-- Apply: wrangler d1 execute <db> --remote --file worker/d1/schema.generated.sql
CREATE TABLE IF NOT EXISTS "t_event_photos" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "image_url" TEXT NOT NULL,
  "storage_path" TEXT,
  "title" TEXT,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "display_order" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_terroir_products" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "category" TEXT,
  "image_url" TEXT,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_payments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "payment_reference" TEXT NOT NULL,
  "user_name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "phone" TEXT,
  "amount" REAL NOT NULL,
  "currency" TEXT NOT NULL DEFAULT 'MAD',
  "payment_method" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "description" TEXT,
  "related_entity_type" TEXT,
  "related_entity_id" TEXT,
  "metadata" TEXT,
  "validated_at" TEXT,
  "validated_by" INTEGER,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_payments_validated_by" ON "t_payments"("validated_by");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_payments_1" ON "t_payments"(payment_reference);
CREATE TABLE IF NOT EXISTS "t_pastry_orders" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "reference" TEXT NOT NULL,
  "customer_name" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "email" TEXT,
  "items" TEXT NOT NULL,
  "total_amount" REAL NOT NULL,
  "payment_method" TEXT NOT NULL,
  "payment_status" TEXT NOT NULL DEFAULT 'pending',
  "order_status" TEXT NOT NULL DEFAULT 'reserved',
  "qr_token" TEXT,
  "scanned_at" TEXT,
  "scanned_by" INTEGER,
  "notes" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_pastry_orders_scanned_by" ON "t_pastry_orders"("scanned_by");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_pastry_orders_1" ON "t_pastry_orders"(reference);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_pastry_orders_2" ON "t_pastry_orders"(qr_token);
CREATE TABLE IF NOT EXISTS "t_feedback_forms" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "title" TEXT,
  "description" TEXT,
  "target_type" TEXT NOT NULL DEFAULT 'global',
  "is_anonymous_allowed" INTEGER NOT NULL DEFAULT 1,
  "active" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_volunteer_participations" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6)))) PRIMARY KEY,
  "email" TEXT NOT NULL,
  "phone" TEXT,
  "event_id" INTEGER,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_shop_order_items" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER,
  "quantity" INTEGER NOT NULL DEFAULT 1,
  "unit_price" REAL NOT NULL,
  "total_price" REAL NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_shop_order_items_order_id" ON "t_shop_order_items"("order_id");
CREATE INDEX IF NOT EXISTS "idx_t_shop_order_items_product_id" ON "t_shop_order_items"("product_id");
CREATE INDEX IF NOT EXISTS "idx_t_shop_order_items_variant_id" ON "t_shop_order_items"("variant_id");
CREATE TABLE IF NOT EXISTS "t_orders" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_reference" TEXT NOT NULL,
  "customer_name" TEXT NOT NULL,
  "customer_email" TEXT NOT NULL,
  "customer_phone" TEXT NOT NULL,
  "total_amount" REAL NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'reserved',
  "pickup_date" TEXT,
  "pickup_location" TEXT,
  "notes" TEXT,
  "processed_by" INTEGER,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "delivery_mode" TEXT NOT NULL DEFAULT 'pickup',
  "delivery_fee" REAL NOT NULL DEFAULT 0,
  "delivery_address" TEXT,
  "delivery_phone" TEXT,
  "delivery_instructions" TEXT,
  "delivered_at" TEXT,
  "payment_method" TEXT DEFAULT 'cash'
);
CREATE INDEX IF NOT EXISTS "idx_t_orders_processed_by" ON "t_orders"("processed_by");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_orders_1" ON "t_orders"(order_reference);
CREATE TABLE IF NOT EXISTS "t_volunteer_profiles" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "first_name" TEXT NOT NULL,
  "last_name" TEXT NOT NULL,
  "phone" TEXT,
  "email" TEXT,
  "role" TEXT NOT NULL DEFAULT 'blue' CHECK ("role" IS NULL OR "role" IN ('blue','orange','yellow','red')),
  "points_total" INTEGER NOT NULL DEFAULT 0,
  "level" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_restaurants" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  "phone" TEXT,
  "capacity" INTEGER DEFAULT 50,
  "active" INTEGER DEFAULT 1,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_partners" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "logo_url" TEXT,
  "website_url" TEXT,
  "description" TEXT,
  "category" TEXT,
  "is_active" INTEGER DEFAULT 1,
  "sort_order" INTEGER DEFAULT 0,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_goodies" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "price" REAL NOT NULL DEFAULT 0,
  "image_url" TEXT,
  "category" TEXT,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "stock" INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "t_goodie_variants" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "goodie_id" INTEGER NOT NULL,
  "size" TEXT,
  "color" TEXT,
  "stock" INTEGER NOT NULL DEFAULT 0,
  "price_modifier" REAL NOT NULL DEFAULT 0,
  "is_available" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_goodie_variants_goodie_id" ON "t_goodie_variants"("goodie_id");
CREATE TABLE IF NOT EXISTS "t_checkins" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "volunteer_id" INTEGER NOT NULL,
  "token" TEXT NOT NULL,
  "scanned_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "validated_by" INTEGER,
  "validation_mode" TEXT NOT NULL DEFAULT 'scan',
  "ip_address" TEXT,
  "user_agent" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_checkins_volunteer_id" ON "t_checkins"("volunteer_id");
CREATE INDEX IF NOT EXISTS "idx_t_checkins_validated_by" ON "t_checkins"("validated_by");
CREATE TABLE IF NOT EXISTS "t_reservation_payment_tokens" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6)))) PRIMARY KEY,
  "reservation_id" INTEGER NOT NULL,
  "token_hash" TEXT NOT NULL,
  "expires_at" TEXT NOT NULL,
  "used_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_reservation_payment_tokens_reservation_id" ON "t_reservation_payment_tokens"("reservation_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_reservation_payment_tokens_1" ON "t_reservation_payment_tokens"(token_hash);
CREATE TABLE IF NOT EXISTS "t_terroir_order_items" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "variant_id" INTEGER,
  "quantity" INTEGER NOT NULL DEFAULT 1,
  "unit_price" REAL NOT NULL,
  "total_price" REAL NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_terroir_order_items_order_id" ON "t_terroir_order_items"("order_id");
CREATE INDEX IF NOT EXISTS "idx_t_terroir_order_items_product_id" ON "t_terroir_order_items"("product_id");
CREATE INDEX IF NOT EXISTS "idx_t_terroir_order_items_variant_id" ON "t_terroir_order_items"("variant_id");
CREATE TABLE IF NOT EXISTS "t_terroir_orders" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_reference" TEXT NOT NULL,
  "customer_name" TEXT NOT NULL,
  "customer_phone" TEXT NOT NULL,
  "customer_email" TEXT,
  "pickup_slot_id" INTEGER,
  "status" TEXT NOT NULL DEFAULT 'created',
  "payment_status" TEXT NOT NULL DEFAULT 'pending',
  "total_amount" REAL NOT NULL,
  "payment_provider" TEXT,
  "payment_reference" TEXT,
  "deposit_deadline" TEXT,
  "deposit_status" TEXT NOT NULL DEFAULT 'pending',
  "qr_token" TEXT,
  "qr_status" TEXT DEFAULT 'inactive',
  "processed_by" INTEGER,
  "processed_at" TEXT,
  "notes" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "catalog_items" TEXT
);
CREATE INDEX IF NOT EXISTS "idx_t_terroir_orders_pickup_slot_id" ON "t_terroir_orders"("pickup_slot_id");
CREATE INDEX IF NOT EXISTS "idx_t_terroir_orders_processed_by" ON "t_terroir_orders"("processed_by");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_terroir_orders_1" ON "t_terroir_orders"(order_reference);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_terroir_orders_2" ON "t_terroir_orders"(qr_token);
CREATE TABLE IF NOT EXISTS "t_ramadan_daily_stats" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "config_id" INTEGER NOT NULL,
  "ramadan_day" INTEGER NOT NULL,
  "gregorian_date" TEXT NOT NULL,
  "beneficiaries_served" INTEGER NOT NULL DEFAULT 0,
  "meals_distributed" INTEGER NOT NULL DEFAULT 0,
  "volunteers_present" INTEGER NOT NULL DEFAULT 0,
  "notes" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_ramadan_daily_stats_config_id" ON "t_ramadan_daily_stats"("config_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_ramadan_daily_stats_1" ON "t_ramadan_daily_stats"(config_id, ramadan_day);
CREATE TABLE IF NOT EXISTS "t_feedback_campaign_recipients" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "campaign_id" INTEGER NOT NULL,
  "email" TEXT NOT NULL,
  "token" TEXT NOT NULL,
  "opened_at" TEXT,
  "submitted_at" TEXT,
  "expires_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now','+30 days')),
  "user_id" INTEGER,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_feedback_campaign_recipients_campaign_id" ON "t_feedback_campaign_recipients"("campaign_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_feedback_campaign_recipients_1" ON "t_feedback_campaign_recipients"(token);
CREATE TABLE IF NOT EXISTS "t_inventory_products" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "product_type" TEXT NOT NULL,
  "source_product_id" INTEGER,
  "source_variant_id" INTEGER,
  "sku" TEXT,
  "barcode" TEXT,
  "name" TEXT NOT NULL,
  "category" TEXT,
  "unit" TEXT NOT NULL DEFAULT 'piece',
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_inventory_products_1" ON "t_inventory_products"(product_type, source_product_id, source_variant_id) WHERE source_product_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS "t_shop_orders" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_reference" TEXT NOT NULL,
  "customer_name" TEXT NOT NULL,
  "customer_email" TEXT NOT NULL,
  "customer_phone" TEXT NOT NULL,
  "total_amount" REAL NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'reserved',
  "pickup_date" TEXT,
  "pickup_location" TEXT,
  "qr_token" TEXT,
  "qr_status" TEXT DEFAULT 'generated',
  "notes" TEXT,
  "processed_by" INTEGER,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_shop_orders_processed_by" ON "t_shop_orders"("processed_by");
CREATE TABLE IF NOT EXISTS "t_shop_product_variants" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "product_id" INTEGER NOT NULL,
  "label" TEXT,
  "size" TEXT,
  "color" TEXT,
  "stock" INTEGER NOT NULL DEFAULT 0,
  "price_modifier" REAL NOT NULL DEFAULT 0,
  "is_available" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_shop_product_variants_product_id" ON "t_shop_product_variants"("product_id");
CREATE TABLE IF NOT EXISTS "t_volunteer_group_requests" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "group_name" TEXT NOT NULL,
  "responsible_name" TEXT NOT NULL,
  "responsible_email" TEXT NOT NULL,
  "responsible_phone" TEXT NOT NULL,
  "estimated_size" INTEGER,
  "day_id" INTEGER NOT NULL,
  "volunteer_slots" TEXT NOT NULL,
  "file_name" TEXT NOT NULL,
  "file_base64" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "rejection_reason" TEXT,
  "reviewed_by" INTEGER,
  "reviewed_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_volunteer_group_requests_day_id" ON "t_volunteer_group_requests"("day_id");
CREATE TABLE IF NOT EXISTS "t_volunteers" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "first_name" TEXT NOT NULL,
  "last_name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "city" TEXT,
  "day_id" INTEGER NOT NULL,
  "qr_token" TEXT NOT NULL,
  "qr_status" TEXT NOT NULL DEFAULT 'generated',
  "status" TEXT NOT NULL DEFAULT 'registered',
  "scanned_at" TEXT,
  "scanned_by" INTEGER,
  "accepted_terms" INTEGER NOT NULL DEFAULT 0,
  "email_sent" INTEGER NOT NULL DEFAULT 0,
  "notes" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "volunteer_slots" TEXT,
  "confirmed_at" TEXT
);
CREATE INDEX IF NOT EXISTS "idx_t_volunteers_day_id" ON "t_volunteers"("day_id");
CREATE INDEX IF NOT EXISTS "idx_t_volunteers_scanned_by" ON "t_volunteers"("scanned_by");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_volunteers_1" ON "t_volunteers"(qr_token);
CREATE TABLE IF NOT EXISTS "t_pastries" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "price" REAL NOT NULL,
  "image_url" TEXT,
  "category" TEXT,
  "active" INTEGER NOT NULL DEFAULT 1,
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "stock" INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "t_reservation_payment_proofs" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6)))) PRIMARY KEY,
  "reservation_id" INTEGER NOT NULL,
  "storage_path" TEXT NOT NULL,
  "uploaded_by_email" TEXT,
  "uploaded_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "status" TEXT NOT NULL DEFAULT 'submitted',
  "admin_note" TEXT
);
CREATE INDEX IF NOT EXISTS "idx_t_reservation_payment_proofs_reservation_id" ON "t_reservation_payment_proofs"("reservation_id");
CREATE TABLE IF NOT EXISTS "t_inventory_locations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "type" TEXT NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "event_id" INTEGER,
  "parent_location_id" INTEGER,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "metadata" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_inventory_locations_event_id" ON "t_inventory_locations"("event_id");
CREATE INDEX IF NOT EXISTS "idx_t_inventory_locations_parent_location_id" ON "t_inventory_locations"("parent_location_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_inventory_locations_1" ON "t_inventory_locations"(code);
CREATE TABLE IF NOT EXISTS "t_reservation_checkins" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "reservation_id" INTEGER,
  "scanned_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "validation_mode" TEXT DEFAULT 'qr_scan',
  "validated_by" INTEGER,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_reservation_checkins_reservation_id" ON "t_reservation_checkins"("reservation_id");
CREATE TABLE IF NOT EXISTS "t_inventory_movements" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "product_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "movement_type" TEXT NOT NULL,
  "from_location_id" INTEGER,
  "to_location_id" INTEGER,
  "event_id" INTEGER,
  "pos_location_id" INTEGER,
  "sale_order_id" TEXT,
  "sale_line_id" TEXT,
  "reference_type" TEXT,
  "reference_id" TEXT,
  "reason" TEXT,
  "note" TEXT,
  "performed_by" INTEGER,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_inventory_movements_product_id" ON "t_inventory_movements"("product_id");
CREATE INDEX IF NOT EXISTS "idx_t_inventory_movements_from_location_id" ON "t_inventory_movements"("from_location_id");
CREATE INDEX IF NOT EXISTS "idx_t_inventory_movements_to_location_id" ON "t_inventory_movements"("to_location_id");
CREATE INDEX IF NOT EXISTS "idx_t_inventory_movements_event_id" ON "t_inventory_movements"("event_id");
CREATE INDEX IF NOT EXISTS "idx_t_inventory_movements_pos_location_id" ON "t_inventory_movements"("pos_location_id");
CREATE INDEX IF NOT EXISTS "idx_t_inventory_movements_performed_by" ON "t_inventory_movements"("performed_by");
CREATE TABLE IF NOT EXISTS "t_terroir_product_variants" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "product_id" INTEGER NOT NULL,
  "label" TEXT NOT NULL,
  "sku" TEXT,
  "price_unit" REAL NOT NULL,
  "stock_total" INTEGER NOT NULL DEFAULT 0,
  "stock_reserved" INTEGER NOT NULL DEFAULT 0,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_terroir_product_variants_product_id" ON "t_terroir_product_variants"("product_id");
CREATE TABLE IF NOT EXISTS "t_terroir_pickup_slots" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "date" TEXT NOT NULL,
  "start_time" TEXT,
  "end_time" TEXT,
  "max_orders" INTEGER,
  "is_closed" INTEGER NOT NULL DEFAULT 0,
  "notes" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_products" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "price" REAL NOT NULL DEFAULT 0,
  "stock" INTEGER NOT NULL DEFAULT 0,
  "image" TEXT,
  "category" TEXT,
  "tags" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'active',
  "product_type" TEXT NOT NULL,
  "is_best_seller" INTEGER NOT NULL DEFAULT 0,
  "is_ramadan_edition" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "images" TEXT
);
CREATE TABLE IF NOT EXISTS "t_payment_logs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "payment_id" INTEGER NOT NULL,
  "action" TEXT NOT NULL,
  "old_status" TEXT,
  "new_status" TEXT,
  "notes" TEXT,
  "performed_by" INTEGER,
  "ip_address" TEXT,
  "user_agent" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_payment_logs_payment_id" ON "t_payment_logs"("payment_id");
CREATE INDEX IF NOT EXISTS "idx_t_payment_logs_performed_by" ON "t_payment_logs"("performed_by");
CREATE TABLE IF NOT EXISTS "t_reservation_events" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6)))) PRIMARY KEY,
  "reservation_id" INTEGER NOT NULL,
  "event_type" TEXT NOT NULL,
  "payload" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_reservation_events_reservation_id" ON "t_reservation_events"("reservation_id");
CREATE TABLE IF NOT EXISTS "t_payment_methods_config" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "method" TEXT NOT NULL,
  "enabled" INTEGER NOT NULL DEFAULT 1,
  "label" TEXT,
  "instructions" TEXT,
  "config" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_payment_methods_config_1" ON "t_payment_methods_config"(method);
CREATE TABLE IF NOT EXISTS "t_inventory_stock_balances" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "product_id" INTEGER NOT NULL,
  "location_id" INTEGER NOT NULL,
  "quantity_on_hand" INTEGER NOT NULL DEFAULT 0,
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_inventory_stock_balances_product_id" ON "t_inventory_stock_balances"("product_id");
CREATE INDEX IF NOT EXISTS "idx_t_inventory_stock_balances_location_id" ON "t_inventory_stock_balances"("location_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_inventory_stock_balances_1" ON "t_inventory_stock_balances"(product_id, location_id);
CREATE TABLE IF NOT EXISTS "t_qr_tokens" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "token" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "entity_id" INTEGER,
  "status" TEXT NOT NULL DEFAULT 'active',
  "max_uses" INTEGER NOT NULL DEFAULT 1,
  "uses_count" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "expires_at" TEXT,
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_qr_tokens_1" ON "t_qr_tokens"(token);
CREATE TABLE IF NOT EXISTS "t_feedback_questions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "form_id" INTEGER NOT NULL,
  "label" TEXT NOT NULL,
  "question" TEXT,
  "type" TEXT NOT NULL,
  "required" INTEGER NOT NULL DEFAULT 0,
  "order_index" INTEGER NOT NULL DEFAULT 0,
  "options" TEXT
);
CREATE INDEX IF NOT EXISTS "idx_t_feedback_questions_form_id" ON "t_feedback_questions"("form_id");
CREATE TABLE IF NOT EXISTS "t_inventory_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "starts_at" TEXT,
  "ends_at" TEXT,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_restaurant_reservations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "reference" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "seats_total" INTEGER NOT NULL,
  "date" TEXT,
  "name" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "email" TEXT,
  "company_name" TEXT,
  "group_name" TEXT,
  "group_type" TEXT,
  "status" TEXT NOT NULL DEFAULT 'submitted',
  "payment_status" TEXT NOT NULL DEFAULT 'not_applicable',
  "payment_amount" REAL,
  "payment_provider" TEXT,
  "payment_reference" TEXT,
  "qr_token" TEXT,
  "qr_status" TEXT DEFAULT 'inactive',
  "expires_at" TEXT,
  "processed_by" INTEGER,
  "processed_at" TEXT,
  "notes" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "deposit_percentage" INTEGER DEFAULT 0,
  "display_choice" TEXT,
  "mode_deposit" TEXT,
  "date_av_reg" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_restaurant_reservations_1" ON "t_restaurant_reservations"(reference);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_restaurant_reservations_2" ON "t_restaurant_reservations"(qr_token);
CREATE TABLE IF NOT EXISTS "t_testimonials" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "role" TEXT,
  "content" TEXT NOT NULL,
  "avatar_url" TEXT,
  "rating" INTEGER DEFAULT 5,
  "is_active" INTEGER DEFAULT 1,
  "sort_order" INTEGER DEFAULT 0,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_order_items" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_id" INTEGER NOT NULL,
  "goodie_id" INTEGER NOT NULL,
  "variant_id" INTEGER,
  "quantity" INTEGER NOT NULL DEFAULT 1,
  "unit_price" REAL NOT NULL,
  "total_price" REAL NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_order_items_order_id" ON "t_order_items"("order_id");
CREATE INDEX IF NOT EXISTS "idx_t_order_items_goodie_id" ON "t_order_items"("goodie_id");
CREATE INDEX IF NOT EXISTS "idx_t_order_items_variant_id" ON "t_order_items"("variant_id");
CREATE TABLE IF NOT EXISTS "t_reservations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "restaurant_id" INTEGER,
  "date" TEXT NOT NULL,
  "slot_id" INTEGER,
  "full_name" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "email" TEXT,
  "seats" INTEGER NOT NULL DEFAULT 1,
  "notes" TEXT,
  "status" TEXT DEFAULT 'confirmed',
  "reference_code" TEXT NOT NULL,
  "qr_token" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_reservations_restaurant_id" ON "t_reservations"("restaurant_id");
CREATE INDEX IF NOT EXISTS "idx_t_reservations_slot_id" ON "t_reservations"("slot_id");
CREATE TABLE IF NOT EXISTS "t_ramadan_config" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "hijri_year" TEXT NOT NULL,
  "gregorian_start_date" TEXT NOT NULL,
  "timezone" TEXT NOT NULL DEFAULT 'Africa/Casablanca',
  "is_active" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_ramadan_config_1" ON "t_ramadan_config"(is_active) where is_active = true;
CREATE TABLE IF NOT EXISTS "t_qr_scans" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "token" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "entity_id" INTEGER,
  "validation_action" TEXT NOT NULL,
  "validated_by" INTEGER NOT NULL,
  "success" INTEGER NOT NULL DEFAULT 1,
  "error_message" TEXT,
  "scanned_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_qr_scans_validated_by" ON "t_qr_scans"("validated_by");
CREATE TABLE IF NOT EXISTS "t_restaurant_slots" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "restaurant_id" INTEGER,
  "date" TEXT NOT NULL,
  "start_time" TEXT,
  "end_time" TEXT,
  "capacity" INTEGER DEFAULT 50,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_restaurant_slots_restaurant_id" ON "t_restaurant_slots"("restaurant_id");
CREATE TABLE IF NOT EXISTS "t_feedback_campaigns" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "title" TEXT,
  "subject" TEXT NOT NULL,
  "email_subject" TEXT,
  "email_content" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "form_id" INTEGER,
  "target_group" TEXT,
  "sent_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_feedback_campaigns_form_id" ON "t_feedback_campaigns"("form_id");
CREATE TABLE IF NOT EXISTS "t_shop_products" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "category" TEXT NOT NULL CHECK ("category" IS NULL OR "category" IN ('patisserie','goodies','terroir')),
  "price" REAL NOT NULL,
  "image_url" TEXT,
  "is_best_seller" INTEGER NOT NULL DEFAULT 0,
  "is_new" INTEGER NOT NULL DEFAULT 0,
  "is_ramadan_edition" INTEGER NOT NULL DEFAULT 0,
  "total_stock" INTEGER,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "sort_order" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_ramadan_days" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "day_number" INTEGER NOT NULL,
  "date" TEXT NOT NULL,
  "hijri_date" TEXT,
  "capacity" INTEGER NOT NULL DEFAULT 120,
  "registered_count" INTEGER NOT NULL DEFAULT 0,
  "is_open" INTEGER NOT NULL DEFAULT 1,
  "iftar_time" TEXT,
  "location" TEXT,
  "notes" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_ramadan_days_1" ON "t_ramadan_days"(day_number);
CREATE UNIQUE INDEX IF NOT EXISTS "uq_t_ramadan_days_2" ON "t_ramadan_days"(date);
CREATE TABLE IF NOT EXISTS "t_feedback_answers" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "response_id" INTEGER NOT NULL,
  "question_id" INTEGER NOT NULL,
  "value" TEXT,
  "answer_text" TEXT,
  "answer_rating" INTEGER,
  "answer_choice" TEXT
);
CREATE INDEX IF NOT EXISTS "idx_t_feedback_answers_response_id" ON "t_feedback_answers"("response_id");
CREATE INDEX IF NOT EXISTS "idx_t_feedback_answers_question_id" ON "t_feedback_answers"("question_id");
CREATE TABLE IF NOT EXISTS "t_feedback_responses" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "form_id" INTEGER,
  "campaign_id" INTEGER,
  "recipient_id" INTEGER,
  "email" TEXT,
  "feedback_type" TEXT,
  "rating" INTEGER,
  "message" TEXT,
  "source" TEXT NOT NULL DEFAULT 'public_page',
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "user_id" INTEGER,
  "user_email" TEXT,
  "user_name" TEXT,
  "is_anonymous" INTEGER NOT NULL DEFAULT 0,
  "moderation" TEXT NOT NULL DEFAULT 'pending'
);
CREATE INDEX IF NOT EXISTS "idx_t_feedback_responses_form_id" ON "t_feedback_responses"("form_id");
CREATE INDEX IF NOT EXISTS "idx_t_feedback_responses_campaign_id" ON "t_feedback_responses"("campaign_id");
CREATE INDEX IF NOT EXISTS "idx_t_feedback_responses_recipient_id" ON "t_feedback_responses"("recipient_id");
CREATE TABLE IF NOT EXISTS "t_volunteer_attendance_view" (
  "id" INTEGER,
  "volunteer_id" TEXT PRIMARY KEY,
  "date" TEXT,
  "slot" TEXT,
  "status" TEXT,
  "points_earned" INTEGER,
  "created_at" TEXT
);
CREATE TABLE IF NOT EXISTS "t_inventory_counts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "location_id" INTEGER NOT NULL,
  "event_id" INTEGER,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "counted_by" INTEGER,
  "started_at" TEXT,
  "completed_at" TEXT,
  "notes" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_inventory_counts_location_id" ON "t_inventory_counts"("location_id");
CREATE INDEX IF NOT EXISTS "idx_t_inventory_counts_event_id" ON "t_inventory_counts"("event_id");
CREATE INDEX IF NOT EXISTS "idx_t_inventory_counts_counted_by" ON "t_inventory_counts"("counted_by");
CREATE TABLE IF NOT EXISTS "t_custom_qr_codes" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "label" TEXT NOT NULL DEFAULT '',
  "url" TEXT NOT NULL,
  "created_by" INTEGER,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_custom_qr_codes_created_by" ON "t_custom_qr_codes"("created_by");
CREATE TABLE IF NOT EXISTS "t_audit_logs" (
  "id" TEXT NOT NULL DEFAULT (lower(hex(randomblob(4)))||'-'||lower(hex(randomblob(2)))||'-4'||substr(lower(hex(randomblob(2))),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(lower(hex(randomblob(2))),2)||'-'||lower(hex(randomblob(6)))) PRIMARY KEY,
  "user_id" TEXT,
  "user_email" TEXT,
  "user_role" TEXT,
  "action" TEXT NOT NULL,
  "entity_type" TEXT,
  "entity_id" TEXT,
  "description" TEXT,
  "metadata" TEXT,
  "ip_address" TEXT,
  "user_agent" TEXT,
  "route" TEXT,
  "http_method" TEXT,
  "response_status" INTEGER,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS "t_inventory_count_lines" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "count_id" INTEGER NOT NULL,
  "product_id" INTEGER NOT NULL,
  "expected_qty" INTEGER NOT NULL DEFAULT 0,
  "counted_qty" INTEGER,
  "variance_qty" INTEGER,
  "note" TEXT,
  "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE INDEX IF NOT EXISTS "idx_t_inventory_count_lines_count_id" ON "t_inventory_count_lines"("count_id");
CREATE INDEX IF NOT EXISTS "idx_t_inventory_count_lines_product_id" ON "t_inventory_count_lines"("product_id");
