// GENERATED by scripts/gen-d1-from-supabase.mjs. Do not edit.
import meta from "./d1/meta.generated.json";

export type ColKind = "int" | "num" | "bool" | "json" | "text";
export interface TableMeta {
  cols: Record<string, ColKind>;
  pk: string[];
  fks: { col: string; ref: string; refCol: string }[];
  cascade: Record<string, string>;
  hasUpdatedAt: boolean;
}
export const META = meta as unknown as Record<string, TableMeta>;
